version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/docker/nginx-proxy/certs:/etc/nginx/certs:ro
      - /srv/docker/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - nginx-proxy-dhparam:/etc/nginx/dhparam
      - nginx-proxy-vhostd:/etc/nginx/vhost.d
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - proxy
    volumes:
      - /srv/docker/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy

